### ISSUE TITLE
Running mobilenet model on myriad.

### ISSUE THREAD

**Issue by kselvan079** [eembc/mlmark#5]
I have followed the steps in the readme file and tried to run the mobilenet 1.0 version on myriad.
I get this error
"FileNotFoundError: [Errno 2] No such file or directory: /mlmark/targets/openvino_ubuntu/workloads/mobilenet/result_Wed172220.txt"

While the same model runs successfully on the CPU. Im provide the snap of error. Would like some help on it.

![Screenshot from 2019-09-04 17-27-44](https://user-images.githubusercontent.com/32350674/64252755-6240a500-cf39-11e9-88b8-c78dfe97dc40.png)

**Comment by petertorelli** [comment]
The problem is further up the screen: image_classification_async, the key binary, is not found. That binary is created when compiling the sources from the instructions listed in the README.md. If that file is not present, the compile step had an error. What happened when you ran compile_MLMARK_sources.sh?

**Comment by kselvan079** [comment]
Hey, thanks for the reply. Apparently the compilation hasn't been completed successfully because of overwritten image_classification_async file. It worked when i deleted that file and tried again. I will close this issue.
